apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deploy-demo-green
  namespace: k8s-demo
  labels:
    app: k8s-deploy-demo
    version: v2
    color: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-deploy-demo
      color: green
  template:
    metadata:
      labels:
        app: k8s-deploy-demo
        version: v2
        color: green
    spec:
      containers:
        - name: app
          image: k8s-deploy-demo:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: APP_STRATEGY
              value: Blue-Green (green)
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
